substitutions:
  deviceName: "atom_1"
  zone: "1"

esphome:
  name: $deviceName
  platform: ESP32
  board: pico32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${deviceName} Fail Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:


ota:
  password: !secret ota_password


mqtt:
  broker: !secret mqtt_broker
  topic_prefix: "Lighting/${deviceName}"
  id: mqtt_client
  




binary_sensor:
  - platform: gpio
    name: "Button"
    id: cbutton
    pin: 39
    internal: true
    filters:
      - invert
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - mqtt.publish:
              topic: "Lighting/Buttons/${deviceName}"
              payload: "DoubleClick"
              qos: 2
      - timing:
          - ON for 1.5s to 8s
          - OFF for at least 0.5s
        then:
          - mqtt.publish:
              topic: "Lighting/Buttons/${deviceName}"
              payload: "LongClick"
              qos: 2
      - timing:
          - ON for at most 1.5s
          - OFF for at least 0.5s
        then:
          - mqtt.publish:
              topic: "Lighting/Buttons/${deviceName}"
              payload: "SingleClick"
              qos: 2
light:
  - platform: neopixelbus
    type: GRB
    pin: 27
    num_leds: 1
    name: "NeoPixel"
    id: neopixel
