substitutions:
  deviceName: "override deviceName from cmdline (-s deviceName <put deviceName value here>)"
  mqtt_topic_prefix: "lighting/buttons/${deviceName}"

esphome:
  name: $deviceName
  platform: ESP32
  board: pico32
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${deviceName} Fail Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:


ota:
  password: !secret ota_password


mqtt:
  broker: !secret mqtt_broker
  topic_prefix: "${mqtt_topic_prefix}"
  id: mqtt_client
  on_message:
    - topic: lighting/buttons/${deviceName}/button_a_state
      qos: 1
      payload: "OFF"
      then:
        - light.turn_on:
            id: neopixel
            brightness: 50%
            red: 100%
            green: 0%
            blue: 0%
    - topic: lighting/buttons/${deviceName}/button_a_state
      qos: 1
      payload: "A"
      then:
        - light.turn_on:
            id: neopixel
            brightness: 50%
            red: 100%
            green: 100%
            blue: 0%
    - topic: lighting/buttons/${deviceName}/button_a_state
      qos: 1
      payload: "B"
      then:
        - light.turn_on:
            id: neopixel
            brightness: 50%
            red: 100%
            green: 100%
            blue: 0%
    - topic: lighting/buttons/${deviceName}/button_a_state
      qos: 1
      payload: "ALL"
      then:
        - light.turn_on:
            id: neopixel
            brightness: 50%
            red: 0%
            green: 100%
            blue: 0%  




binary_sensor:
  - platform: gpio
    name: "Button"
    id: cbutton
    pin: 39
    internal: true
    filters:
      - invert
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - mqtt.publish:
              topic: "${mqtt_topic_prefix}/button_a"
              payload: "DoubleClick"
              qos: 2
      - timing:
          - ON for 1.5s to 8s
          - OFF for at least 0.5s
        then:
          - mqtt.publish:
              topic: "${mqtt_topic_prefix}/button_a"
              payload: "LongClick"
              qos: 2
      - timing:
          - ON for at most 1.5s
          - OFF for at least 0.5s
        then:
          - mqtt.publish:
              topic: "${mqtt_topic_prefix}/button_a"
              payload: "SingleClick"
              qos: 2
light:
  - platform: neopixelbus
    type: GRB
    variant: 800KBPS
    pin: 27
    num_leds: 1
    name: "NeoPixel"
    id: neopixel
