substitutions:
  deviceName: "remote_switch_1"
  zone: "1"

esphome:
  name: $deviceName
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${deviceName} Fail Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:


ota:
  password: !secret ota_password


spi:
  clk_pin: 5
  mosi_pin: 23
  
font:
  - file: "fonts/impact.ttf"
    id: impact_font_70
    size: 70
  - file: "fonts/impact.ttf"
    id: impact_font_35
    size: 35
  
color:
   - id: on_color_bkg
     red: 0%
     green: 100%
     blue: 0%
   - id: off_color_bkg
     red: 100%
     green: 0%
     blue: 0%
   - id: pending_off_color_bkg
     red: 75%
     green: 25%
     blue: 10%

     
display:
  - platform: st7735
    model: "INITR_GREENTAB"
    reset_pin: 9
    cs_pin: 16
    dc_pin: 17
    rotation: 90
    device_width: 130
    device_height: 130
    col_start: 0
    row_start: 0
    eight_bit_color: true
    use_bgr: true
    update_interval: 5s
    id: main_display
    pages:
      - id: on_page
        lambda: |-
          it.fill(id(on_color_bkg));
          it.print(25, 20, id(impact_font_70), Color(0,0,0), TextAlign::TOP_LEFT, "ON");
      - id: off_page
        lambda: |-
          it.fill(id(off_color_bkg));
          it.print(20, 20, id(impact_font_70), Color(0,0,0), TextAlign::TOP_LEFT, "OFF");
      - id: pending_off_page
        lambda: |-
          it.fill(id(pending_off_color_bkg));
          it.print(5, 15, id(impact_font_35), Color(0,0,0), TextAlign::TOP_LEFT, "PENDING");
          it.print(45, 60, id(impact_font_35), Color(0,0,0), TextAlign::TOP_LEFT, "OFF");

mqtt:
  broker: !secret mqtt_broker
  topic_prefix: "Lighting/${deviceName}"
  id: mqtt_client
  on_message:
    - topic: "Lighting/LZ${zone}_Sts"
      payload: "On"
      qos: 1
      then:
        - display.page.show: on_page
        - component.update: main_display
    - topic: "Lighting/LZ${zone}_Sts"
      payload: "Off"
      qos: 1
      then:
        - display.page.show: off_page            
        - component.update: main_display
    - topic: "Lighting/LZ${zone}_Sts"
      payload: "Pending_Off"
      qos: 1
      then:
        - display.page.show: pending_off_page            
        - component.update: main_display




binary_sensor:
  - platform: gpio
    name: "A Button"
    id: a_button
    pin: 34
    internal: true
  - platform: gpio
    name: "B Button"
    id: b_button
    pin: 35
    internal: true
    on_press:
      then:
        - mqtt.publish:
            topic: "Lighting/LZ${zone}_Cmd"
            payload: "On"
            qos: 1
  - platform: gpio
    name: "C Button"
    id: c_button
    pin: 39
    internal: true
    on_press:
      then:
        - mqtt.publish:
            topic: "Lighting/LZ${zone}_Cmd"
            payload: "Off"
            qos: 1

